services:
  app:
    build: .
    ports:
      - 127.0.0.1:8009:8080
    environment:
      REDIS_HOST: redis
    stop_grace_period: 0s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  
  redis:
    image: redis:latest
    stop_grace_period: 0s
    resources:
    limits:
      memory: 1GB
    logging:
      driver: "json-file"
      options:
        max-size: "1m"